### ISSUE TITLE
Panic for `command list` without args

### ISSUE THREAD

**Issue by wiggin77** [mattermost/mmctl#128]
./mmctl command list
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/mattermost/mmctl/commands.listCommandCmdF(0xbffac0, 0xc0000dcb90, 0x102d400, 0x1057d30, 0x0, 0x0, 0xc0000bee80, 0xc000123cb8)
	/home/dlauder/Development/mattermost/mmctl/commands/command.go:204 +0x671
github.com/mattermost/mmctl/commands.withClient.func1(0x102d400, 0x1057d30, 0x0, 0x0, 0x0, 0x0)
	/home/dlauder/Development/mattermost/mmctl/commands/init.go:58 +0x125
github.com/spf13/cobra.(*Command).execute(0x102d400, 0x1057d30, 0x0, 0x0, 0x102d400, 0x1057d30)
	/home/dlauder/Development/mattermost/mmctl/vendor/github.com/spf13/cobra/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x102a200, 0xb05c4b, 0x1a, 0xbf0d00)
	/home/dlauder/Development/mattermost/mmctl/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/dlauder/Development/mattermost/mmctl/vendor/github.com/spf13/cobra/command.go:864
github.com/mattermost/mmctl/commands.Run(0xc0000a8070, 0x2, 0x2, 0x8c380, 0xc00009a058)
	/home/dlauder/Development/mattermost/mmctl/commands/root.go:29 +0x4f3
main.main()
	/home/dlauder/Development/mattermost/mmctl/mmctl.go:13 +0x68

**Comment by wiggin77** [comment]
Fixed via https://github.com/mattermost/mmctl/pull/129
